### ISSUE TITLE
Automated Container For Certs Renewal

### ISSUE THREAD

**Issue by pwdel** [openpredictionmarkets/socialpredict#197]
Basically we have a set up wherein we're using an nginx container as our frontend:

https://github.com/openpredictionmarkets/socialpredict/blob/bb5c86e3e351e077a881f26944b1bae61bd795ca/docker-compose.prod.yaml#L28

and so we're able to successfully host on HTTP, however we need to create a sustainable way so that anyone who uses this open source software can have access to automatically renewable SSL certs, perhaps via a certbot container which creates certs that gets mounted to the nginx container via a volume.

See how it's done here for ideas:

https://bitbucket.org/JoeHitchen/gatekeeper/src/master/docker-compose.yml

So essentially, there are two containers which tie into one another:

```
  nginx:
    image: nginx
    network_mode: host
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./webroot:/var/www/gatekeeper
      - cert_data:/etc/letsencrypt
      - challenge:/var/www/challenge

  certbot:
    image: certbot/certbot
    volumes:
      - cert_data:/etc/letsencrypt
      - cert_logs:/var/lib/letsencrypt
      - challenge:/var/www/challenge
    command: renew
    depends_on:
      - nginx 

volumes:
  cert_data:
  cert_logs:
  challenge:
```

Another idea to look at:

https://github.com/SteveLTN/https-portal
